spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managepatients
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

#  security:
#    user:
#      name: saman
#      password: 1234